version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 127.0.0.1:9200:9200
    environment:
      # Disable bootstrap checks so users don't have to fiddle with
      # vm.max_map_count. Note that this file is not used in production
      # deployments; bootstrap checks are still enabled for production
      # deployments.
      - "transport.host=localhost"
  app:
    build:
      context: .
    environment:
      # Show prints right away. See
      # http://tarunlalwani.com/post/why-delayed-output-python-docker/
      - "PYTHONUNBUFFERED=1"
