name: Repro https://github.com/nektos/act/issues/1072
on:
  workflow_dispatch:

jobs:
  sleep:
    name: Sleep
    runs-on: ubuntu-latest
    steps:

    - name: Sleep
      run: |
        echo "Before sleep"
        sleep 100000
        echo "After sleep"
